SRC += kern/init.c          \
       kern/stdlib.c        \
       kern/acpi.c          \
       kern/debug/ubsan.c   \
       kern/debug/serial.c  \
       kern/debug/kasan.c   \
       kern/heap.c          \
       kern/list.c          \
       kern/sched.c         \
       kern/task.c          \
       kern/thread.c        \
       kern/sys.c           \
       kern/tree.c          \
       kern/fs/vfs.c        \
       kern/fs/open.c       \
       kern/fs/readwr.c     \
       kern/fs/fcntl.c      \
       kern/fs/ioctl.c      \
       kern/fs/readdir.c    \
       kern/fs/mount.c      \
       kern/fs/devfs.c      \
       kern/mm/mmap.c       \
       kern/exit.c          \
       kern/exec.c          \
       kern/fork.c          \
       kern/signal.c        \
       kern/time.c          \
       kern/binfmt.c        \
       kern/ps2.c           \
       kern/module.c        \
       kern/fbdev.c         \
       kern/tty.c           \
       kern/vga.c           \
       kern/ringbuf.c       \
       kern/ksym.c          \
       kern/pci.c           \
       kern/dev.c           \
       kern/ptrace.c